import type { OrderFormConfig } from "./types";

export const CS2_PREMIER_CONFIG: OrderFormConfig = {
  title: "Premier Rating Boost",
  tabs: [
    { id: "solo", label: "Solo Queue" },
    { id: "duo", label: "Duo Queue" },
  ],
  currentValue: {
    label: "Current Rating",
    min: 0,
    max: 30000,
    step: 1000,
    defaultValue: 5000,
  },
  desiredValue: {
    label: "Desired Rating",
    min: 0,
    max: 30000,
    step: 1000,
    defaultValue: 10000,
  },
  options: [
    {
      id: "selfPlay",
      label: "Self Play",
      tooltip: "Play together with the booster on your account",
      priceModifier: 40,
      modifierType: "percentage",
    },
    {
      id: "priority",
      label: "Priority",
      tooltip: "Your order gets priority in the queue",
      priceModifier: 20,
      modifierType: "percentage",
    },
    {
      id: "superExpress",
      label: "Super Express",
      tooltip: "Fastest possible completion time",
      priceModifier: 50,
      modifierType: "percentage",
    },
    {
      id: "soloOnly",
      label: "Solo Only",
      tooltip: "Booster plays solo queue only",
      priceModifier: 10,
      modifierType: "percentage",
    },
    {
      id: "liveStream",
      label: "Live Stream",
      tooltip: "Watch the booster play live",
      priceModifier: 15,
      modifierType: "percentage",
    },
    {
      id: "ghostMode",
      label: "Ghost Mode",
      tooltip: "Appear offline during the entire boost",
      priceModifier: 5,
      modifierType: "percentage",
    },
  ],
  currency: "\u20AC",
  basePricePerUnit: 0.01,
  cashbackPercent: 5,
  discountTiers: [
    { threshold: 50, discount: 2 },
    { threshold: 100, discount: 3 },
    { threshold: 200, discount: 5 },
    { threshold: 500, discount: 8 },
  ],
  estimatedTime: "24\u201372 hours",
  boosterAssignTime: "~15 minutes",
};

export const CS2_FACEIT_CONFIG: OrderFormConfig = {
  title: "Faceit Level Boost",
  currentValue: {
    label: "Current Level",
    min: 1,
    max: 10,
    step: 1,
    defaultValue: 3,
    formatValue: (v) => `Level ${v}`,
  },
  desiredValue: {
    label: "Desired Level",
    min: 1,
    max: 10,
    step: 1,
    defaultValue: 7,
    formatValue: (v) => `Level ${v}`,
  },
  options: [
    {
      id: "selfPlay",
      label: "Self Play",
      tooltip: "Play together with the booster",
      priceModifier: 40,
      modifierType: "percentage",
    },
    {
      id: "priority",
      label: "Priority",
      tooltip: "Your order gets priority in the queue",
      priceModifier: 20,
      modifierType: "percentage",
    },
    {
      id: "superExpress",
      label: "Super Express",
      tooltip: "Fastest possible completion",
      priceModifier: 50,
      modifierType: "percentage",
    },
    {
      id: "liveStream",
      label: "Live Stream",
      tooltip: "Watch the booster play live",
      priceModifier: 15,
      modifierType: "percentage",
    },
    {
      id: "ghostMode",
      label: "Ghost Mode",
      tooltip: "Appear offline during the boost",
      priceModifier: 5,
      modifierType: "percentage",
    },
  ],
  currency: "\u20AC",
  basePricePerUnit: 18,
  cashbackPercent: 5,
  discountTiers: [
    { threshold: 40, discount: 2 },
    { threshold: 80, discount: 3 },
    { threshold: 150, discount: 5 },
  ],
  estimatedTime: "24\u201396 hours",
  boosterAssignTime: "~15 minutes",
};

/* ─── CS2 ESEA ─── */

const ESEA_RANKS = [
  "D-",
  "D",
  "D+",
  "C-",
  "C",
  "C+",
  "B-",
  "B",
  "B+",
  "A-",
  "A",
  "A+",
];

export const CS2_ESEA_CONFIG: OrderFormConfig = {
  title: "ESEA Rank Boost",
  currentValue: {
    label: "Current Rank",
    min: 0,
    max: 11,
    step: 1,
    defaultValue: 0,
    formatValue: (v) => ESEA_RANKS[v] ?? ESEA_RANKS[0],
  },
  desiredValue: {
    label: "Desired Rank",
    min: 0,
    max: 11,
    step: 1,
    defaultValue: 6,
    formatValue: (v) => ESEA_RANKS[v] ?? ESEA_RANKS[0],
  },
  options: [
    {
      id: "selfPlay",
      label: "Self Play",
      tooltip: "Play together with the booster",
      priceModifier: 40,
      modifierType: "percentage",
    },
    {
      id: "priority",
      label: "Priority",
      tooltip: "Your order gets priority",
      priceModifier: 20,
      modifierType: "percentage",
    },
    {
      id: "superExpress",
      label: "Super Express",
      tooltip: "Fastest completion time",
      priceModifier: 50,
      modifierType: "percentage",
    },
    {
      id: "liveStream",
      label: "Live Stream",
      tooltip: "Watch the booster play",
      priceModifier: 15,
      modifierType: "percentage",
    },
  ],
  currency: "\u20AC",
  basePricePerUnit: 20,
  cashbackPercent: 5,
  discountTiers: [
    { threshold: 50, discount: 2 },
    { threshold: 100, discount: 3 },
    { threshold: 200, discount: 5 },
  ],
  estimatedTime: "24\u201372 hours",
  boosterAssignTime: "~15 minutes",
};

/* ─── Dota 2 MMR ─── */

export const DOTA2_MMR_CONFIG: OrderFormConfig = {
  title: "MMR Boost",
  currentValue: {
    label: "Current MMR",
    min: 0,
    max: 12000,
    step: 100,
    defaultValue: 2000,
  },
  desiredValue: {
    label: "Desired MMR",
    min: 0,
    max: 12000,
    step: 100,
    defaultValue: 3500,
  },
  options: [
    {
      id: "selfPlay",
      label: "Self Play",
      tooltip: "Play on your account with the booster",
      priceModifier: 40,
      modifierType: "percentage",
    },
    {
      id: "priority",
      label: "Priority",
      tooltip: "Your order gets priority",
      priceModifier: 20,
      modifierType: "percentage",
    },
    {
      id: "superExpress",
      label: "Super Express",
      tooltip: "Fastest possible completion",
      priceModifier: 50,
      modifierType: "percentage",
    },
    {
      id: "soloOnly",
      label: "Solo Only",
      tooltip: "Booster plays solo queue only",
      priceModifier: 10,
      modifierType: "percentage",
    },
    {
      id: "liveStream",
      label: "Live Stream",
      tooltip: "Watch the booster play live",
      priceModifier: 15,
      modifierType: "percentage",
    },
  ],
  extraSections: [
    {
      id: "role",
      type: "select",
      label: "Preferred Role",
      options: [
        { value: "any", label: "Any Role" },
        { value: "carry", label: "Carry (Safe Lane)" },
        { value: "mid", label: "Mid Lane" },
        { value: "offlane", label: "Offlane" },
        { value: "support", label: "Soft Support" },
        { value: "hard_support", label: "Hard Support" },
      ],
    },
  ],
  currency: "\u20AC",
  basePricePerUnit: 0.015,
  cashbackPercent: 5,
  discountTiers: [
    { threshold: 30, discount: 2 },
    { threshold: 60, discount: 3 },
    { threshold: 120, discount: 5 },
    { threshold: 300, discount: 8 },
  ],
  estimatedTime: "48\u201396 hours",
  boosterAssignTime: "~20 minutes",
};

/* ─── Valorant Rank ─── */

const VALORANT_RANKS_LIST = [
  "Iron 1",
  "Iron 2",
  "Iron 3",
  "Bronze 1",
  "Bronze 2",
  "Bronze 3",
  "Silver 1",
  "Silver 2",
  "Silver 3",
  "Gold 1",
  "Gold 2",
  "Gold 3",
  "Platinum 1",
  "Platinum 2",
  "Platinum 3",
  "Diamond 1",
  "Diamond 2",
  "Diamond 3",
  "Ascendant 1",
  "Ascendant 2",
  "Ascendant 3",
  "Immortal 1",
  "Immortal 2",
  "Immortal 3",
  "Radiant",
];

export const VALORANT_RANK_CONFIG: OrderFormConfig = {
  title: "Rank Boost",
  currentValue: {
    label: "Current Rank",
    min: 0,
    max: 24,
    step: 1,
    defaultValue: 3,
    formatValue: (v) => VALORANT_RANKS_LIST[v] ?? VALORANT_RANKS_LIST[0],
  },
  desiredValue: {
    label: "Desired Rank",
    min: 0,
    max: 24,
    step: 1,
    defaultValue: 9,
    formatValue: (v) => VALORANT_RANKS_LIST[v] ?? VALORANT_RANKS_LIST[0],
  },
  options: [
    {
      id: "selfPlay",
      label: "Self Play",
      tooltip: "Play on your account with the booster",
      priceModifier: 40,
      modifierType: "percentage",
    },
    {
      id: "priority",
      label: "Priority",
      tooltip: "Your order gets priority",
      priceModifier: 20,
      modifierType: "percentage",
    },
    {
      id: "superExpress",
      label: "Super Express",
      tooltip: "Fastest completion time",
      priceModifier: 50,
      modifierType: "percentage",
    },
    {
      id: "liveStream",
      label: "Live Stream",
      tooltip: "Watch the booster play",
      priceModifier: 15,
      modifierType: "percentage",
    },
  ],
  currency: "\u20AC",
  basePricePerUnit: 8,
  cashbackPercent: 5,
  discountTiers: [
    { threshold: 30, discount: 2 },
    { threshold: 60, discount: 3 },
    { threshold: 120, discount: 5 },
  ],
  estimatedTime: "24\u201372 hours",
  boosterAssignTime: "~15 minutes",
};
